global:
    smtp_smarthost: 'email-smtp.us-west-2.amazonaws.com:587'
    smtp_from: 'Alertmanager <alertmanager@example.com>'
    smtp_auth_username: 'FILLMEIN'
    smtp_auth_password: 'FILLMEIN'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  receiver: 'team-mails'